spring:
  profiles:
    active: dev
  application:
    name: xhh-ro-client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.200:3306/xhh
    username: root
    password: mysql910416
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-idle: 5
      initial-size: 5
      max-wait-millis: 10000
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      validation-query: select 1 from dual
  http:
    multipart:
      maxRequestSize: 100Mb
      maxFileSize: 100Mb
  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQLDialect
    #hibernate:
    #  naming:
    #    implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    #    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
  redis:
    port: 6379
    host: 127.0.0.1
    
server:
  port: 28602
  jsp-servlet:
    init-parameters:
      development: true

logging:
  config: classpath:logback-spring.xml
  
  
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://192.168.0.50:28001/eureka/
  instance: 
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
      
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic
        
hystrix:
    command:
        default:
            execution:
              timeout:
                enabled: true
              isolation:
                    thread:
                        timeoutInMilliseconds: 15000
