spring:
  profiles:
    active: dev
  application:
    name: xhh-elk-kafka
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.1:3306/xhh
    username: root
    password: mysql910416
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-idle: 5
      initial-size: 5
      max-wait-millis: 10000
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      validation-query: select 1 from dual
  http:
    multipart:
      maxRequestSize: 100Mb
      maxFileSize: 100Mb
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 127.0.0.1

#============== kafka ===================
# 指定kafka 代理地址，可以多个
  kafka:
    bootstrap-servers: 192.168.0.50:9092
    producer:
      retries: 0
#每次批量发送消息的数量
      batch-size: 16384
      buffer-memory: 33554432
# 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
# 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    
server:
  port: 28901
  jsp-servlet:
    init-parameters:
      development: true

logging:
  config: classpath:logback-spring.xml

eureka:
  client: 
    serviceUrl: 
      defaultZone: http://192.168.0.50:28001/eureka/
  instance: 
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
      
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic
        
hystrix:
    command:
        default:
            execution:
              timeout:
                enabled: true
              isolation:
                    thread:
                        timeoutInMilliseconds: 15000
                        

